spring.datasource.url=jdbc:postgresql://localhost:5432/hw_bot
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml






